name: Monthly scrape (self-hosted Windows)

on:
  schedule:
    - cron: "0 0 1 * *"          # 00:00 UTC on the 1st of each month
  workflow_dispatch: {}          # allow manual runs

jobs:
  run:
    # must match the labels you assigned when you ran: .\config.cmd --labels windows,self-hosted
    runs-on: [self-hosted, windows]

    env:
      # adjust as you like
      REGIONS: "ZA-WC-CT"
      STORE: "CHECKERS"
      INGREDIENTS_JSON: '["cheddar cheese","milk","beef mince"]'
      # windows path for the service account key
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}\gcp-key.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        shell: pwsh
        run: |
          python -m playwright install

      - name: Write Firebase service account key
        shell: pwsh
        run: |
          $key = '${{ secrets.GCP_SA_KEY }}'
          Set-Content -Path $env:GOOGLE_APPLICATION_CREDENTIALS -Value $key -Encoding ascii

      - name: Run scraper
        shell: pwsh
        run: |
          python scrape_prices.py

      - name: Upload debug artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: debug-html
          path: debug/*
          if-no-files-found: ignore
